# Generated by Django 3.1 on 2024-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bookauthors',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bookloans',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='borrower',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fines',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='email', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='Username', max_length=100),
        ),
    ]
